# Build settings
markdown: kramdown
permalink: pretty
# debugmode: true

exclude: ["git-untracked"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      section-group: "secondary"
      layout: "default"

# Site settings
title: basimilch
description: Genossenschaft basimilch - Die kooperative Käserei in Dietikon
baseurl: ""
url: "http://basimil.ch"

info:
    name: Genossenschaft basimilch
    shortname: basimilch
    subtitle: Die kooperative Käserei in Dietikon
    email: info@basimil.ch
    address:
        street: Alte Kindhauserstrasse 3
        plz: 8953
        city: Dietikon ZH
        url: https://www.google.ch/maps/place/Alte+Kindhauserstrasse+3+8953+Dietikon+Switzerland

github:
    repo:
        branch: as-jekyll
        url: https://github.com/basimilch/basimilch.github.io
